import React, { useState } from 'react';
import {
  Sparkles,
  AlertTriangle,
  Lightbulb,
  CheckCircle2,
  Clock,
  ExternalLink,
  ChevronDown,
  ChevronUp,
  FileText,
} from 'lucide-react';
import { StrategicInsight } from '../types/intelligence.ts';

interface InsightsPageProps {
  insights: StrategicInsight[];
  onOpenEvidence: (evidenceId: string) => void;
}

export const InsightsPage: React.FC<InsightsPageProps> = ({ insights, onOpenEvidence }) => {
  const [expandedId, setExpandedId] = useState<string | null>(insights[0]?.id || null);

  return (
    <div className="space-y-6 pb-12 animate-in fade-in duration-300">
      {/* Header */}
      <div className="border-b border-slate-800 pb-4">
        <h2 className="text-lg font-bold text-white tracking-tight flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-indigo-400" />
          <span>Strategic Synthesis & Market Intelligence</span>
        </h2>
        <p className="text-xs text-slate-400">
          Synthesized dossiers generated by combining verified observations with persistent Hindsight memory. Distinguishes observed facts from strategic interpretations.
        </p>
      </div>

      <div className="space-y-6">
        {insights.map((ins) => {
          const isExpanded = expandedId === ins.id;
          return (
            <div
              key={ins.id}
              className="bg-slate-900 border border-slate-800 rounded-xl overflow-hidden shadow-sm transition hover:border-slate-700"
            >
              {/* Header Card */}
              <div
                onClick={() => setExpandedId(isExpanded ? null : ins.id)}
                className="p-5 cursor-pointer bg-slate-900/90 flex items-start justify-between gap-4 select-none"
              >
                <div className="space-y-1.5 max-w-3xl">
                  <div className="flex items-center gap-2">
                    <span className="text-xs font-bold text-indigo-400 tracking-wide uppercase">
                      {ins.competitorName || 'Cross-Competitor'}
                    </span>
                    <span className="text-[10px] font-mono text-slate-400 bg-slate-800 px-2 py-0.5 rounded">
                      Horizon: {ins.coverageStart} → {ins.coverageEnd}
                    </span>
                    {ins.isStale && (
                      <span className="text-[10px] font-bold text-rose-300 bg-rose-950 px-2 py-0.5 rounded border border-rose-800">
                        STALE (PENDING REGENERATION)
                      </span>
                    )}
                  </div>
                  <h3 className="text-base font-bold text-white leading-snug">{ins.title}</h3>
                  <p className="text-xs text-slate-300 leading-relaxed">{ins.summary}</p>
                </div>

                <button className="text-slate-400 hover:text-slate-200 mt-1">
                  {isExpanded ? <ChevronUp className="w-5 h-5" /> : <ChevronDown className="w-5 h-5" />}
                </button>
              </div>

              {/* Expanded Deep Dossier */}
              {isExpanded && (
                <div className="border-t border-slate-800 p-5 bg-slate-950/70 space-y-5 text-xs">
                  {/* 1. Observed Changes (Facts) */}
                  <div className="space-y-2">
                    <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">
                      1. Verified Observed Facts (Chronological)
                    </span>
                    <div className="space-y-1.5">
                      {ins.observedChanges.map((change, idx) => (
                        <div key={idx} className="flex items-start gap-2 text-slate-200">
                          <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400 mt-0.5 shrink-0" />
                          <span>{change}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* 2. Historical Pattern (Hindsight Memory Connection) */}
                  <div className="p-3.5 rounded-lg bg-indigo-950/40 border border-indigo-800/60 space-y-1.5">
                    <span className="text-xs font-bold text-indigo-300 uppercase tracking-wider block">
                      2. Historical Strategic Pattern (Interpretation)
                    </span>
                    <p className="text-slate-200 leading-relaxed text-xs">{ins.historicalPattern}</p>
                  </div>

                  {/* 3. Business Significance */}
                  <div className="space-y-1.5">
                    <span className="text-[11px] font-bold uppercase tracking-wider text-slate-400 block">
                      3. Business Significance to Our Product & Accounts
                    </span>
                    <p className="text-slate-300 leading-relaxed bg-slate-900 p-3 rounded-lg border border-slate-800">
                      {ins.businessSignificance}
                    </p>
                  </div>

                  {/* 4. Risks & Opportunities */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="p-3.5 rounded-lg bg-slate-900 border border-slate-800 space-y-2">
                      <div className="flex items-center gap-1.5 text-rose-400 font-semibold text-xs">
                        <AlertTriangle className="w-3.5 h-3.5" />
                        <span>Identified Risks</span>
                      </div>
                      <ul className="list-disc list-inside space-y-1 text-slate-300">
                        {ins.risks.map((risk, idx) => (
                          <li key={idx}>{risk}</li>
                        ))}
                      </ul>
                    </div>

                    <div className="p-3.5 rounded-lg bg-slate-900 border border-slate-800 space-y-2">
                      <div className="flex items-center gap-1.5 text-emerald-400 font-semibold text-xs">
                        <Lightbulb className="w-3.5 h-3.5" />
                        <span>Strategic Opportunities</span>
                      </div>
                      <ul className="list-disc list-inside space-y-1 text-slate-300">
                        {ins.opportunities.map((opp, idx) => (
                          <li key={idx}>{opp}</li>
                        ))}
                      </ul>
                    </div>
                  </div>

                  {/* 5. Recommended Concrete Actions */}
                  <div className="space-y-2">
                    <span className="text-[11px] font-bold uppercase tracking-wider text-indigo-400 block">
                      5. Recommended Next Steps
                    </span>
                    <div className="space-y-1.5">
                      {ins.recommendedActions.map((action, idx) => (
                        <div key={idx} className="p-2.5 rounded bg-slate-900 border border-slate-800 flex items-start gap-2">
                          <span className="w-4 h-4 rounded-full bg-indigo-600 text-white flex items-center justify-center text-[10px] font-bold shrink-0 mt-0.5">
                            {idx + 1}
                          </span>
                          <span className="text-slate-200">{action}</span>
                        </div>
                      ))}
                    </div>
                  </div>

                  {/* 6. Alternative Explanations & Uncertainty */}
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-slate-800 text-[11px] text-slate-400">
                    <div>
                      <span className="font-semibold text-slate-300 block mb-0.5">Alternative Explanations:</span>
                      {ins.alternativeExplanations.map((alt, idx) => (
                        <p key={idx}>• {alt}</p>
                      ))}
                    </div>
                    <div>
                      <span className="font-semibold text-slate-300 block mb-0.5">Coverage & Uncertainty:</span>
                      <p>{ins.uncertainty}</p>
                    </div>
                  </div>

                  {/* Citations Footer */}
                  <div className="flex flex-wrap items-center gap-2 pt-2 border-t border-slate-800">
                    <span className="text-[11px] text-slate-500 font-medium">Evidence Grounding:</span>
                    {ins.evidenceIds.map((evId) => (
                      <button
                        key={evId}
                        onClick={() => onOpenEvidence(evId)}
                        className="px-2 py-0.5 rounded bg-slate-800 hover:bg-slate-700 text-indigo-300 text-[10px] font-mono flex items-center gap-1"
                      >
                        <FileText className="w-2.5 h-2.5" />
                        <span>Evidence #{evId.replace('evi-', '')}</span>
                      </button>
                    ))}
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
};
